# Config Map
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: maxam-configmap
data:
  # Configuration values can be set as key-value properties
  hostname: 139.59.47.89
  username: raZorOpsK8s_UsEr
  password: raZorOpsK8s_UsErpAssWd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxam-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maxam-app
  template:
    metadata:
      labels:
        app: maxam-app
    spec:
      containers:
      - name: maxam-app
        image: registry.digitalocean.com/maxamrazo/maxamrazo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
        env:
        - name: MYSQL_DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: maxam-configmap
              key: hostname
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: maxam-configmap
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: maxam-configmap
              key: password
      imagePullSecrets:
      - name: do-registry 
        
---
  apiVersion: v1
  kind: Service
  metadata:
    name: maxam-deployment
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
    selector:
      app: maxam-app
